
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      /bin/bash -c "poetry run python manage.py migrate &&
                    poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    container_name: ${POSTGRES_CONTAINER_NAME}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: