# Generated by Django 5.1.6 on 2025-03-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_uploadedfile_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('images', 'Images'), ('documents', 'Documents'), ('videos', 'Videos'), ('audio', 'Audio'), ('archives', 'Archives'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
