# Generated by Django 5.1.6 on 2025-03-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_uploadedfile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='resource_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
